version: "3"

services:
  postgres:
    image: postgres:latest
    volumes:
    - /data/postgres:/data/postgres
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: user
        POSTGRES_DB: hierarchy_db
    ports:
      - 5432:5432


